name: Build and run tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-latest
          platform: windows
        - os: ubuntu-latest
          platform: linux
        - os: macos-15
          platform: macos

    steps:
    - name: сheckout
      uses: actions/checkout@main

    - name: dir
      run: mkdir -p tools

    - name: mplc
      shell: bash
      run: |
        if [[ "${{ matrix.platform }}" == 'windows' ]]; then
          curl -LSs -o tools/mplc.exe https://github.com/Matway/mpl-c/releases/latest/download/mplc.exe;
        elif [[ "${{ matrix.platform }}" == 'macos' ]]; then
          curl -LSfs -o tools/mplc https://cloud.gravilink.org/s/cgKoT8bLwkcQN9y/download/mplc && chmod +x tools/mplc;
        else
          curl -LSfs -o tools/mplc https://github.com/Matway/mpl-c/releases/latest/download/mplc && chmod +x tools/mplc;
        fi

    - name: test
      shell: bash
      run: if [[ "${{ matrix.platform }}" == 'windows' ]]; then ./test.bat tools/mplc; else ./test.sh ./tools/mplc "${{ matrix.platform }}"; fi

    - name: artifacts
      uses: actions/upload-artifact@main
      with:
        name: tests-${{ matrix.os }}
        path: |
          out/
          tools/mplc
          tools/mplc.exe
